#sudo: false
#dist: precise
dist: bionic

env:
  global:
    - REAHLWORKSPACE=$HOME
    - EMAIL=noone@example.org
    - DEBFULLNAME="Travis Tester"
    - DEBEMAIL=$EMAIL
    - DISPLAY=:99.0
    - PATH=$HOME/bin:$PATH

  matrix:
    include:
      - python: 3.5
        TOX_ENV=py35
      - python: 3.6
        TOX_ENV=py36
      - python: 3.7
        TOX_ENV=py37
      - python: 3.8
        TOX_ENV=py38
      - python: 3.9
        TOX_ENV=py39

addons:
  postgresql: "10"
  apt:
    packages:
       # Basic apt dependencies
        - openssh-client 
        - dpkg-dev
        - bzr
        - git
        - firefox
        - firefox-geckodriver

       # For compiling pip installed extensions we use
        - python-virtualenv
        - python-dev
        - gcc
        - cython
        - libxml2-dev
        - libxslt-dev
        - libsqlite3-0
        - sqlite3
        - postgresql-server-dev-all 
        - zlib1g-dev
        - libjpeg62-dev
        - libfreetype6-dev
        - liblcms2-dev
        - libmysqlclient-dev

        # - phantomjs  # for reference... not allowed in apt addon
       # For testing of reahl-component
        - graphviz

services:
  - xvfb
  - postgresql
  #- mysql

language: python
python:
  - 3.5

cache: 
  pip: true
  directories:
    - $HOME/testinstalls
    - $HOME/.cache/pip

before_install: 
  # Make git happy
  - "travis/setupTestGit.sh"

  # Version checks of these things are useful for debugging
  - git --version
  - firefox --version
  - geckodriver --version
  - gpg --version
  
install:
  - "python scripts/bootstrap.py --script-dependencies"
  - CFLAGS="-O0" python scripts/bootstrap.py --pip-installs
  - "reahl createdb -U postgres reahl-web/etc"
  - "reahl setup -sX -- develop -N"

before_script:
  # Setup pip.conf to use local egg-dist also where we build stuff (for tox to get them)
  - "travis/configurePip.sh"

  # Setup ssh for password-less access to localhost
  - "travis/createTestSshKey.sh"
  - "travis/createTestGpgKey.sh"
  - "(reahl build -sdX || (EXITCODE=$?; shred -f $HOME/.gnupg/*; exit $EXITCODE))"

script:
  - "(reahl shell -sdXg tox -e $TOX_ENV && (EXITCODE=$?; shred -f $HOME/.gnupg/*; exit $EXITCODE))"

before_deploy:
  - travis/configurePypi.sh

deploy:
  provider: script
  script: reahl upload -rusdX
  on:
    tags: true
    condition: "$TOX_ENV = py36"
